
#ifndef __ENUM_SPRITE__
#define __ENUM_SPRITE__

#define dfDELAY_STAND	5
#define dfDELAY_MOVE	4
#define dfDELAY_ATTACK1	3
#define dfDELAY_ATTACK2	4
#define dfDELAY_ATTACK3	4
#define dfDELAY_EFFECT	3

enum class e_SPRITE 
{
	//MAP
	eMAP,

	//STAND_L
	ePLAYER_STAND_L_01,
	ePLAYER_STAND_L_02,
	ePLAYER_STAND_L_03,
	ePLAYER_STAND_L_MAX,

	//STAND_R
	ePLAYER_STAND_R_01,
	ePLAYER_STAND_R_02,
	ePLAYER_STAND_R_03,
	ePLAYER_STAND_R_MAX,

	//MOVE_L
	ePLAYER_MOVE_L_01,
	ePLAYER_MOVE_L_02,
	ePLAYER_MOVE_L_03,
	ePLAYER_MOVE_L_04,
	ePLAYER_MOVE_L_05,
	ePLAYER_MOVE_L_06,
	ePLAYER_MOVE_L_07,
	ePLAYER_MOVE_L_08,
	ePLAYER_MOVE_L_09,
	ePLAYER_MOVE_L_10,
	ePLAYER_MOVE_L_11,
	ePLAYER_MOVE_L_MAX,

	//MOVE_R
	ePLAYER_MOVE_R_01,
	ePLAYER_MOVE_R_02,
	ePLAYER_MOVE_R_03,
	ePLAYER_MOVE_R_04,
	ePLAYER_MOVE_R_05,
	ePLAYER_MOVE_R_06,
	ePLAYER_MOVE_R_07,
	ePLAYER_MOVE_R_08,
	ePLAYER_MOVE_R_09,
	ePLAYER_MOVE_R_10,
	ePLAYER_MOVE_R_11,
	ePLAYER_MOVE_R_MAX,

	//ATTACK1_L
	ePLAYER_ATTACK1_L_01,
	ePLAYER_ATTACK1_L_02,
	ePLAYER_ATTACK1_L_03,
	ePLAYER_ATTACK1_L_MAX,

	//ATTACK1_R
	ePLAYER_ATTACK1_R_01,
	ePLAYER_ATTACK1_R_02,
	ePLAYER_ATTACK1_R_03,
	ePLAYER_ATTACK1_R_MAX,

	//ATTACK2_L
	ePLAYER_ATTACK2_L_01,
	ePLAYER_ATTACK2_L_02,
	ePLAYER_ATTACK2_L_03,
	ePLAYER_ATTACK2_L_MAX,

	//ATTACK2_R
	ePLAYER_ATTACK2_R_01,
	ePLAYER_ATTACK2_R_02,
	ePLAYER_ATTACK2_R_03,
	ePLAYER_ATTACK2_R_MAX,

	//ATTACK3_L
	ePLAYER_ATTACK3_L_01,
	ePLAYER_ATTACK3_L_02,
	ePLAYER_ATTACK3_L_03,
	ePLAYER_ATTACK3_L_04,
	ePLAYER_ATTACK3_L_MAX,

	//ATTACK3_R
	ePLAYER_ATTACK3_R_01,
	ePLAYER_ATTACK3_R_02,
	ePLAYER_ATTACK3_R_03,
	ePLAYER_ATTACK3_R_04,
	ePLAYER_ATTACK3_R_MAX,

	//EFFECT
	eEFFECT_SPARK_01,
	eEFFECT_SPARK_02,
	eEFFECT_SPARK_03,
	eEFFECT_SPARK_MAX,

	//SHADOW
	eSHADOW,

	//HPGUAGE
	eGUAGE_HP,

};

#endif __ENUM_SPRITE__
